baseurl = "/"
title = "Geekjournal"
copyright = "Copyright (c) 2017, all rights reserved."
canonifyurls = true
languageCode = "en-US"
paginate = 3
theme = "hugo-dusk"

googleAnalytics = "UA-112468329-1"
disqusShortname = ""

[author]
  name = "Geekjournal Admin"

SectionPagesMenu = "main"

# use Chroma for syntax highlight
pygmentsStyle = "native" # other dark style options: vim, fruity, monokai
# enable syntax highlight for code blocks
pygmentsCodeFences = true

[[menu.main]]
  name = "Posts"
  weight = -120
  identifier = "post"
  url = "/post/"

[[menu.main]]
  name = "Tags"
  weight = -110
  identifier = "tag"
  url = "/tags/"

[params.meta]
  keywords = "blog, tech, computers, software, programming, business"
  description = "Geekjournal is a personal blog."

[params]
  github = "geekjournal"
 # gitlab = "gitlab id"
  twitter = "@realgeekjournal"
 # linkedin = "linkedin id"
  email = "admin <at> geekjournal . com"

[params.colors]
  # hugo-dusk colors
  background = "#FFFFFF" # background color for the site
  # this includes the title
  main = "#000000"   
  title = "#0000FF"
  text = "#000000"
  code-quote-bg = "#FFFFFF" # background color for quotes and code blocks
  pre = "#1166FF"
  copyright = "#404040" # copyright text color
  disqusShortName = "geekjournal" # whatever you set up on Disqus
